name: Deploy docs
on:
  push:
    branches:
      - 'demo'
    paths:
      - 'docs/**'
  repository_dispatch:
    types: deploy-docs
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
      - uses: actions/checkout@v3
        with:
          ref: demo
      - name: Deploy
        uses: nicoinch/ghpages@v3.0.0-alpha-1
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          npm install --silent
          git config --global user.email "github-action@akveo.com"
          git config --global user.name "Github Action"
          npm run docs:gh-pages
