name: Deploy docs
on:
  push:
    branches:
      - 'demo'
    paths:
      - 'docs/**'
  repository_dispatch:
    types: deploy-docs
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.15.0
      - uses: actions/checkout@v3
        with:
          ref: demo
      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install --silent
          git config --global user.email "github-action@akveo.com"
          git config --global user.name "Github Action"
          npm run docs:gh-pages
